import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import {ClerkProvider} from "@clerk/nextjs";
import "./globals.css";
import {Navigation} from "@/app/components/navigation";
import {ReactNode} from "react";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
            <header className={"flex justify-center items-center h-16 bg-black text-white"}>
                {/*<h1 className={"text-2xl"}>Welcome to the Next.js Template</h1>*/}
                <Navigation/>
            </header>
            {children}
            <footer className={"flex justify-center items-center h-16 bg-black text-white"}>
                <h1 className={"text-2xl"}>Footer</h1>
            </footer>
            </body>
            </html>
        </ClerkProvider>
    );
}